swagger: "2.0"
info:
  description: A file is a computer resource allowing storage of data
    that is being processed. The interface to a file provides the
    mechanism to appropriately locate a file in a distributed
    system. File identification includes the name, endpoint, checksum,
    and size. Additional parameters, such as the last access time,
    could also be stored. The interface only describes the location of
    the file.  The file object has name, endpoint (location), size in
    GB, MB, Byte, checksum for integrity check, and last accessed
    timestamp.
  version: "1.0.0"
  title: file
consumes:
  - application/json
produces:
  - application/json

basePath: /cloudmesh_data

paths:
  /files/{provider}:
    get:
      description: Returns all files from a specific provider
      operationId: file.get_files
      parameters:
        - name: service
          in: path
          type: string
          required: True
      produces:
        - application/json
      responses:
        '200':
          description: file list
          schema:
            $ref: '#/definitions/File'
  /file/{provider}:
    get:
      description: Returns a file for a specifc provider
      operationId: file.get_file_by_name
      parameters:
        - name: service
          in: path
          type: string
          required: True
        - name: filename
          in: query
          required: true
          type: string
        - name: user_uuid
          in: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: file info
          schema:
            $ref: '#/definitions/File'
    post:
      description: Upload a file to a provider
      operationId: file.upload_file_by_name
      parameters:
        - name: service
          in: path
          type: string
          required: True
        - name: filename
          in: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: file uploaded
          schema:
            $ref: '#/definitions/File'
  /file/copy:
    post:
      description: Copy a file to a provider
      operationId: file.copy_file
      parameters:
        - name: filename
          in: query
          required: true
          type: string
        - name: service
          in: query
          type: string
          required: True
        - name: dest
          in: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: file copied
          schema:
            $ref: '#/definitions/File'
  /file/rsync:
    post:
      description: Rsync a file to another directory
      operationId: file.rsync_file
      parameters:
        - name: filename
          in: query
          required: true
          type: string
        - name: service
          in: query
          type: string
          required: true
        - name: dest
          in: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: file synced
          schema:
            $ref: '#/definitions/File'
  /file/delete:
    delete:
      description: Delete a file from a directory
      operationId: file.delete_file
      parameters:
        - name: service
          in: query
          required: true
          type: string
        - name: bucketname
          in: query
          type: string
          required: true
        - name: filename
          in: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: file deleted
          schema:
            $ref: '#/definitions/File'
definitions:
  File:
    type: object
    description: the file
    properties:
      name:
        type: string
        description: the name of the file
      endpoint:
        type: string
        description: The location of the file
      checksum:
        type: string
        description: The checksum of the file
      size:
        type: integer
        description: The size of the file in byte
      timestamp:
        type: string
        description: The timestamp
      last_modified:
        type: string
        description: The timestamp
      user_uuid:
        type: string
        description: uuid of the user having permission
      file_content:
        type: string
        description: file content
