.PHONY: test

server:
	python cloudmesh_data/data/server.py

file:
	echo TODO

test:
	@head -c 79 /dev/zero |tr '\0' '#'
	@echo
	@echo  TEST
	@head -c 79 /dev/zero |tr '\0' '#'
	@echo
	@echo
	test/test.sh

